### ISSUE TITLE
Share host's docker image library?

### ISSUE THREAD

**Issue by cboettig** [mattgruter/dockerfile-drone#3]
Thanks for providing this dockerfile, I'm very impressed by your clever, straight-forward trick to get docker to run on top of docker.  

I'm not sure if I've got this right, but it appears that in this setup, launched the way you indicate in the readme, that drone is maintaining it's own library of docker images, rather than sharing with the host.  Usually that would seem like the desired behavior, keeping drone largely isolated in it's own container.  However, when deploying on a server with limited or costly disk-space, it's tempting to just want drone to use the library of docker images I have on my host anyway.  It seems it should be straight-forward enough to link the volume used for the library of the container to the library of the host, but I'm not sure I could do it successfully and not sure if this would create potential problems.  

Otherwise, this has been working perfectly for me.  Many thanks again.

**Comment by mattgruter** [comment]
Thanks for the feedback. Great that the image is working for you!

Sorry for the late reply. The only way that I'm aware of to share docker image libraries is by means of repositories. You can either push all your images from your host to the public [Docker Hub](https://hub.docker.com/) or to a private Docker registry (https://github.com/docker/docker-registry).

That way the Docker daemon in the drone image will still have local copies of the images being used though. So it's not really a solution to preserve disk-space.

Setting up a private registry is however outside the scope of this image. Therefore I am closing this issue.

Cheers!

**Comment by so0k** [comment]
instead of installing docker in docker, why not volume mount the docker client runtime and socket when launching the container?

```
docker run -it --privileged \
  -v /usr/bin/docker:/usr/bin/docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 \
```

does drone require the docker deamon to be installed locally?

**Comment by cboettig** [comment]
@so0k Yup, linking the docker socket works just fine for me.  Also works just fine without `--privileged` just using the Dockerfile provided from the drone team themselves: 

e.g. I run: 

```
git clone https://github.com/drone/drone.git
cd drone && docker build -t drone/drone .
docker run --name drone -v /var/run/docker.sock:/var/run/docker.sock \
-v /opt/drone:/var/lib/drone \
-t -e DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT} \
-e DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET} \
-p ${DRONE}:80 drone/drone
```

which results in sharing the docker library with the host (and the second `-v` is just for persistent sqlite database).

**Comment by so0k** [comment]
Ok, thanks for clarification, so we don't really need that Docker in Docker trick (anymore)

**Comment by davidwindell** [comment]
Yep, not really needed anymore as mounting the socket as a volume does the trick and doesn't require privs. I've got drone to push to https://registry.hub.docker.com/u/drone/drone/
